SUPABASE_URL = "https://dixibjnybfvcdjleogqq.supabase.co"
SUPABASE_KEY = "sb_publishable_9CANjqW4SixX5eOYU8dLVA_rTSASCw9"
# Contraseña que te estaba dando el error:
PASSWORD_COSTOS = "Sunscreen1241"
# Agrega estas líneas que te están faltando localmente:
PASSWORD_ADMIN = "Sunscreen1241"

TELEFONO_VENTAS = "5492944160866"